[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0B6E4F"
backgroundColor = "#FFE8E8"
secondaryBackgroundColor = "#FFD6D6"
textColor = "#1A1A1A"
font = "sans serif"
