[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF57BD"
backgroundColor = "#FEB1E0"
secondaryBackgroundColor = "#FF57BD"
textColor = "#1A1A1A"
font = "sans serif"
